# Netlify configuration file
[build]
  command = "bash ./netlify.sh && npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["markdown-pdf", "phantomjs-prebuilt"]

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Allow direct function access
[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure all routes go to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200onfiguration file
[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
