# Netlify configuration file
[build]
  command = "bash ./netlify.sh && npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"
  
[functions]
  # Use esbuild for faster builds
  node_bundler = "esbuild"
  
  # Don't bundle these modules (they contain native code)
  external_node_modules = ["markdown-pdf", "phantomjs-prebuilt"]
  
  # Increase timeout for PDF generation
  [functions.convert]
    timeout = 30

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Allow direct function access
[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure all routes go to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
